run:
  # timeout for analysis
  timeout: 4m

  # Linting uses a lot of memory. Keep it under control by only running a single
  # worker.
  concurrency: 1

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

linters:

  # Specify an enabled list of linters rather than a disabled list because
  # the latest linter includes many sub-linters which do not pass the codebase.
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

issues:
  exclude-rules:
    - path: internal/test
      linters:
        - goconst
